### ISSUE TITLE
explore github actions to build/push container

### ISSUE THREAD

**Issue by brito-rafa** [WillBolduc05/imageToPortugueseTile#18]
Submilestone: merge request triggers docker build and docker push (to docker hub or quay).

https://github.com/docker/build-push-action

create a subdir `.github` and a dir under called `workflows`

Example of code:

```
name: Pull Request
on:
  pull_request:
    branches: ['main']

jobs:
  go:
    name: Go
    uses: X/.github/.github/workflows/pull-request-go.yaml@main
    secrets:
      gh-token: ${{ secrets.SERVICES_PACKAGE_PAT }}

  helm:
    name: Helm
    uses: X/.github/.github/workflows/pull-request-helm.yaml@main
    with:
      check-version-increment: false
      check-install: false


  envtest:
    name: Full Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Test
      # Skip lint since that's hanlded by pull-request-go and seems to often be the
      # source of build flakes when run twice
      run: make generate fmt vet test-full
```

another example:

```
name: Main

on:
  workflow_call:
    inputs:
      build-args:
        description: 'Build arguments for the image'
        required: false
        default: ''
        type: string
    secrets:
      gh-token:
        description: 'PAT used for pushing GHCR images.'
        required: true

jobs:

  # Builds and pushes images to GHCR.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and Push
      uses: X/.github/.github/actions/build-push@main
      with:
        build-args: '${{ inputs.build-args }}'
        gh-token: '${{ secrets.gh-token }}'
```

Another example:

```
name: 'Build Push'
description: 'Builds and pushes a Docker image to GHCR.'
inputs:
  gh-token:
    description: 'PAT used for triggering workflows.'
    required: true
  build-args:
    description: 'Build arguments for the image'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

  - uses: docker/setup-buildx-action@v2

  - uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: '${{ github.actor }}'
      password: '${{ github.token }}'

  - uses: docker/metadata-action@v4
    id: meta
    with:
      images: ghcr.io/${{ github.repository }}
      flavor: latest=false
      tags: type=sha

  - uses: docker/build-push-action@v4
    with:
      context: .
      push: true
      provenance: false
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha
      build-args: ${{ inputs.build-args }}

  - shell: bash
    env:
      GH_REPO: gramLabs/stormforge-app
      GH_TOKEN: ${{ inputs.gh-token }}
    run: |
      gh workflow run promote_image_to_dev.yaml \
        -f image="${{ steps.meta.outputs.tags }}"
```
